### ISSUE TITLE
Search new repo owner

### ISSUE THREAD

**Issue by sedx** [navinspm/clndr-rails#5]
I'm no more using CLNDR. It's a bit hard to maintain gem when you not using them. In this case I will be happy to transfer repository to someone, who regularly use Rails and CLNDR.

I hope in new hands gem will be grow up and evolve better that in mine.

**Comment by casecamp** [comment]
I would like to update the gem for rails 5.0.1 and maintain

**Comment by navinspm** [comment]
I would like to update the gem to work with rails 5 and maintain.

**Comment by sedx** [comment]
@navinspm Hi! thanks for response! I initiated transfer to yours account. Gem was been written when I begin my way with Rails and Ruby and can contain some strange code and solutions, sorry for that. Also added you to gem's owners on the rubygems.org

**Comment by navinspm** [comment]
@sedx Thanks, what are the changes , features you would like to do with clndr-rails?. I will do them whenever I got time.

**Comment by sedx** [comment]
@navinspm Sorry, but I'm not used gem a lot of time (it was one of reason to find new maintainer) and have no ideas and road map about further development of gem.  So feel free to bring yours ideas and vision.
